# в данном случае пока для теста сделали так,потом нужно будет указывать полный ci cd с докер файлами в папках фронтенде и бэкэнда
# здесь описаны все стадии для джобов(типа билд(сборка),тест,деплой и тд),они будут запускаться по порядку сверху вниз,следющий не запустится,пока предыдущий не закончил
stages:
  - test

# здесь указываем название джобы
test-job:
  # здесь указываем название стадии(которую мы указывали чуть выше в поле stages) для этой джобы  
  stage: test
  script:
    - echo "Test job"